### ISSUE TITLE
Pins don't federate

### ISSUE THREAD

**Issue by FitikWasTaken** [MbinOrg/mbin#442] opened 2024-01-16 13:28 UTC
**Describe the bug**
Original bug report on kbin - https://codeberg.org/Kbin/kbin-core/issues/1180
(Pinned threads are not federated across magazines/communities)

**On which Mbin instance did you find the bug?**
fedia.io

**To Reproduce**
1. Go to kbin magazine - https://kbin.social/m/kbinMeta
Or to Lemmy community -
https://lemmy.world/c/piracy@lemmy.dbzer0.com
3. See that it has pinned threads
4. Go to the mbin magazine from mbin  - https://fedia.io/m/kbinMeta@kbin.social
Or to the lemmy community from mbin  - https://fedia.io/m/piracy@lemmy.dbzer0.com
6. See that pins aren't federated

**Expected behavior**
Ability to see pinned posts(threads/microblogs) in communities and magazines on top

**Additional context**
Additionally, mbin could implement pinned posts(threads/microblogs) on profiles and they could be federated as well.

**Comment by BentiGorlich** [comment] 2024-01-17 13:56
Duplicate of #248

**Closed by BentiGorlich** 2024-01-17 13:56 UTC
Labels: bug
